name: Mateusz Myalski
url: https://mateuszmyalski.github.io
description: The real OS fits in a floppy disk.

permalink: /:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
